"""Theme definitions for Koke16-Bit Studio.

Each theme is a dict of colour tokens consumed by the QSS template in
``build_qss()``.  A colour-mode (``"dark"`` or ``"light"``) selects base
brightness, then the *visual theme* overrides accent colours, radii,
borders, fonts, and extra QSS snippets.
"""
from __future__ import annotations

from dataclasses import dataclass, field


# ────────────────────────────────────────────────────────────────────
# Token dataclass that every theme provides
# ────────────────────────────────────────────────────────────────────

@dataclass
class ThemeTokens:
    # Colour mode the tokens were built for
    mode: str = "dark"                  # "dark" | "light"

    # Base surfaces
    bg_window: str = "#101010"
    bg_panel: str = "#111111"
    bg_input: str = "#121212"
    bg_hover: str = "#181818"
    bg_selected: str = "#1a2e2a"

    # Text
    fg_primary: str = "#e7e7e7"
    fg_secondary: str = "#aaaaaa"
    fg_muted: str = "#777777"
    fg_disabled: str = "#555555"

    # Accent
    accent: str = "#00ffc8"
    accent_hover: str = "#00ffc8"
    accent_bg: str = "#1a2e2a"

    # Borders
    border: str = "#343434"
    border_panel: str = "#292929"
    border_input: str = "#2a2a2a"
    border_separator: str = "#2e2e2e"
    border_item: str = "#1a1a1a"

    # Buttons
    btn_bg: str = "#1f1f1f"

    # Danger / active
    danger: str = "#ff4444"
    mute_active: str = "#e74c3c"
    solo_active: str = "#f1c40f"

    # Rounding
    radius: str = "6px"
    radius_panel: str = "8px"

    # Title
    title_size: str = "20px"

    # Font family (empty = inherit theme default)
    font_family: str = "Segoe UI"

    # Extra QSS appended verbatim after the generated base sheet
    extra_qss: str = ""


# ────────────────────────────────────────────────────────────────────
# QSS template builder
# ────────────────────────────────────────────────────────────────────

def build_qss(t: ThemeTokens) -> str:
    """Render a full application QSS string from *t*."""
    return f"""
/* ── Generated by Koke16-Bit Studio theme engine ── */

QMainWindow, QWidget {{
    background: {t.bg_window};
    color: {t.fg_primary};
    font-family: {t.font_family};
}}

QPushButton {{
    background: {t.btn_bg};
    border: 1px solid {t.border};
    border-radius: {t.radius};
    padding: 6px 10px;
}}
QPushButton:hover {{ border-color: {t.accent}; color: {t.accent}; }}
QPushButton:checked {{ border-color: {t.accent}; color: {t.accent}; }}
QPushButton#playing {{ border-color: {t.danger}; color: {t.danger}; }}

QListWidget {{
    background: {t.bg_input};
    border: 1px solid {t.border_input};
    border-radius: {t.radius};
}}
QListWidget::item {{
    padding: 2px 4px;
    border-bottom: 1px solid {t.border_item};
}}
QListWidget::item:selected {{
    background: {t.bg_selected};
    border-left: 3px solid {t.accent};
}}
QListWidget::item:hover {{ background: {t.bg_hover}; }}

QFrame#panel {{
    background: {t.bg_panel};
    border: 1px solid {t.border_panel};
    border-radius: {t.radius_panel};
}}

QLabel#title {{
    color: {t.accent};
    font-size: {t.title_size};
    font-weight: 700;
}}
QLabel#trackName {{ font-size: 12px; font-weight: 600; color: {t.fg_primary}; }}
QLabel#trackMeta {{ font-size: 10px; color: {t.fg_muted}; }}
QLabel#trackRole {{ font-size: 10px; font-weight: 700; border-radius: 3px; padding: 1px 5px; }}

QProgressBar#volumeBar {{
    background: {t.border_item};
    border: none;
    border-radius: 2px;
    max-height: 4px;
}}
QProgressBar#volumeBar::chunk {{
    background: {t.accent};
    border-radius: 2px;
}}

QRadioButton {{ color: {t.fg_primary}; spacing: 6px; }}
QRadioButton::indicator {{
    width: 14px; height: 14px;
    border: 2px solid {t.fg_disabled};
    border-radius: 9px;
    background: {t.border_item};
}}
QRadioButton::indicator:hover {{ border-color: {t.accent}; }}
QRadioButton::indicator:checked {{
    border-color: {t.accent};
    background: {t.accent};
}}
QRadioButton::indicator:checked:hover {{
    background: {t.accent};
    border-color: {t.accent};
}}
QRadioButton:disabled {{ color: {t.fg_disabled}; }}
QRadioButton::indicator:disabled {{ border-color: #333333; background: {t.border_item}; }}

QCheckBox {{ color: {t.fg_primary}; spacing: 6px; }}
QCheckBox::indicator {{
    width: 14px; height: 14px;
    border: 2px solid {t.fg_disabled};
    border-radius: 3px;
    background: {t.border_item};
}}
QCheckBox::indicator:hover {{ border-color: {t.accent}; }}
QCheckBox::indicator:checked {{
    border-color: {t.accent};
    background: {t.accent};
}}

QProgressDialog {{ min-width: 420px; }}

QComboBox {{
    background: {t.btn_bg};
    border: 1px solid {t.border};
    border-radius: {t.radius};
    padding: 4px 8px;
    color: {t.fg_primary};
}}
QComboBox:hover {{ border-color: {t.accent}; }}
QComboBox QAbstractItemView {{
    background: {t.bg_input};
    border: 1px solid {t.border};
    selection-background-color: {t.accent_bg};
    selection-color: {t.accent};
}}

QSpinBox {{
    background: {t.btn_bg};
    border: 1px solid {t.border};
    border-radius: {t.radius};
    padding: 3px 6px;
    color: {t.fg_primary};
}}
QSpinBox:hover {{ border-color: {t.accent}; }}

QSlider::groove:horizontal {{
    border: none;
    height: 4px;
    background: {t.border_input};
    border-radius: 2px;
}}
QSlider::handle:horizontal {{
    background: {t.accent};
    border: none;
    width: 12px;
    height: 12px;
    margin: -4px 0;
    border-radius: 6px;
}}
QSlider::sub-page:horizontal {{
    background: {t.accent};
    border-radius: 2px;
}}

QTabWidget::pane {{
    border: 1px solid {t.border_panel};
    background: {t.bg_panel};
    border-radius: {t.radius};
}}
QTabBar::tab {{
    background: {t.btn_bg};
    border: 1px solid {t.border};
    border-bottom: none;
    border-top-left-radius: {t.radius};
    border-top-right-radius: {t.radius};
    padding: 5px 12px;
    color: {t.fg_secondary};
}}
QTabBar::tab:selected {{
    background: {t.bg_panel};
    color: {t.accent};
    border-bottom: 2px solid {t.accent};
}}
QTabBar::tab:hover {{ color: {t.accent}; }}

QSplitter::handle {{
    background: {t.border_separator};
    width: 2px;
}}

QStatusBar {{
    background: {t.bg_panel};
    color: {t.fg_muted};
    border-top: 1px solid {t.border_panel};
}}

QScrollBar:vertical {{
    background: {t.bg_input};
    width: 10px;
    border-radius: 5px;
}}
QScrollBar::handle:vertical {{
    background: {t.border};
    min-height: 30px;
    border-radius: 5px;
}}
QScrollBar::handle:vertical:hover {{ background: {t.accent}; }}
QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {{ height: 0; }}

QScrollBar:horizontal {{
    background: {t.bg_input};
    height: 10px;
    border-radius: 5px;
}}
QScrollBar::handle:horizontal {{
    background: {t.border};
    min-width: 30px;
    border-radius: 5px;
}}
QScrollBar::handle:horizontal:hover {{ background: {t.accent}; }}
QScrollBar::add-line:horizontal, QScrollBar::sub-line:horizontal {{ width: 0; }}

QMessageBox {{
    background: {t.bg_panel};
}}
QMessageBox QLabel {{
    color: {t.fg_primary};
}}

QDialog {{
    background: {t.bg_panel};
    color: {t.fg_primary};
}}

QMenu {{
    background: {t.bg_panel};
    border: 1px solid {t.border};
    border-radius: {t.radius};
    padding: 4px;
}}
QMenu::item {{
    padding: 6px 24px;
    border-radius: 4px;
}}
QMenu::item:selected {{
    background: {t.accent_bg};
    color: {t.accent};
}}

{t.extra_qss}
"""


# ────────────────────────────────────────────────────────────────────
# Built-in theme catalogue
# ────────────────────────────────────────────────────────────────────

def _dark_base() -> ThemeTokens:
    return ThemeTokens()


def _light_base() -> ThemeTokens:
    return ThemeTokens(
        mode="light",
        bg_window="#f5f5f5", bg_panel="#ffffff", bg_input="#fafafa",
        bg_hover="#eaeaea", bg_selected="#d6f5ed",
        fg_primary="#1a1a1a", fg_secondary="#555555",
        fg_muted="#888888", fg_disabled="#bbbbbb",
        accent="#00b894", accent_hover="#00a884", accent_bg="#d6f5ed",
        border="#cccccc", border_panel="#dddddd", border_input="#d0d0d0",
        border_separator="#d0d0d0", border_item="#e8e8e8",
        btn_bg="#ffffff",
        danger="#e74c3c",
    )


# ── Actual visual themes ──────────────────────────────────────

def _retro_neon(base: ThemeTokens) -> ThemeTokens:
    """The original Koke16 default — neon cyan on deep black."""
    # Already the default dark tokens; just label it.
    return base


def _aero_glass(base: ThemeTokens) -> ThemeTokens:
    """Windows Vista / 7 Aero-inspired translucent look."""
    base.accent = "#4fc3f7"
    base.accent_hover = "#29b6f6"
    base.accent_bg = "#1a2940" if base.mode == "dark" else "#d4ecf7"
    base.bg_selected = base.accent_bg
    base.radius = "4px"
    base.radius_panel = "6px"
    base.extra_qss = f"""
QFrame#panel {{
    background: {"rgba(20,30,50,0.82)" if base.mode == "dark" else "rgba(220,235,255,0.88)"};
    border: 1px solid {"rgba(120,180,255,0.35)" if base.mode == "dark" else "rgba(100,160,220,0.4)"};
}}
QLabel#title {{ color: {base.accent}; }}
"""
    return base


def _win11(base: ThemeTokens) -> ThemeTokens:
    """Windows 11 / Fluent-style — soft rounded corners, mica-like surfaces."""
    base.radius = "8px"
    base.radius_panel = "12px"
    base.accent = "#60cdff" if base.mode == "dark" else "#005fb8"
    base.accent_hover = "#4cc2ff" if base.mode == "dark" else "#004f9e"
    base.accent_bg = "#1a2d3d" if base.mode == "dark" else "#d4e8f8"
    base.bg_selected = base.accent_bg
    if base.mode == "dark":
        base.bg_window = "#1c1c1c"
        base.bg_panel = "#2d2d2d"
        base.bg_input = "#242424"
        base.btn_bg = "#2d2d2d"
        base.border = "#3d3d3d"
        base.border_panel = "#3d3d3d"
    else:
        base.bg_window = "#f3f3f3"
        base.bg_panel = "#ffffff"
        base.btn_bg = "#fbfbfb"
        base.border = "#e0e0e0"
        base.border_panel = "#e0e0e0"
    base.font_family = "Segoe UI Variable, Segoe UI"
    base.extra_qss = f"""
QPushButton {{ border-radius: 6px; padding: 6px 14px; }}
QLabel#title {{ color: {base.accent}; }}
"""
    return base


def _macos(base: ThemeTokens) -> ThemeTokens:
    """macOS / Aqua-inspired — rounded, muted, with system-like accent."""
    base.radius = "10px"
    base.radius_panel = "14px"
    base.accent = "#007aff" if base.mode == "dark" else "#007aff"
    base.accent_hover = "#409cff" if base.mode == "dark" else "#005ecb"
    base.accent_bg = "#182848" if base.mode == "dark" else "#d4e4ff"
    base.bg_selected = base.accent_bg
    if base.mode == "dark":
        base.bg_window = "#1e1e1e"
        base.bg_panel = "#2a2a2a"
        base.bg_input = "#252525"
        base.btn_bg = "#323232"
        base.border = "#444444"
        base.border_panel = "#3a3a3a"
    else:
        base.bg_window = "#ececec"
        base.bg_panel = "#ffffff"
        base.btn_bg = "#ffffff"
        base.border = "#c8c8c8"
        base.border_panel = "#d4d4d4"
    base.font_family = "SF Pro Display, Helvetica Neue, Segoe UI"
    base.extra_qss = f"""
QPushButton {{ border-radius: 8px; padding: 5px 14px; }}
QLabel#title {{ color: {base.accent}; }}
"""
    return base


def _dos(base: ThemeTokens) -> ThemeTokens:
    """CGA/DOS retro terminal style — sharp edges, monospace, bold colours."""
    base.radius = "0px"
    base.radius_panel = "0px"
    base.font_family = "Consolas, Courier New, monospace"
    base.title_size = "18px"
    if base.mode == "dark":
        base.bg_window = "#000080"
        base.bg_panel = "#000060"
        base.bg_input = "#000050"
        base.bg_hover = "#0000a0"
        base.bg_selected = "#00aa00"
        base.fg_primary = "#ffffff"
        base.fg_secondary = "#aaaaaa"
        base.fg_muted = "#555555"
        base.accent = "#ffff00"
        base.accent_hover = "#ffff55"
        base.accent_bg = "#004400"
        base.border = "#808080"
        base.border_panel = "#808080"
        base.border_input = "#808080"
        base.btn_bg = "#000080"
        base.danger = "#ff0000"
    else:
        base.bg_window = "#c0c0c0"
        base.bg_panel = "#d0d0d0"
        base.bg_input = "#ffffff"
        base.bg_hover = "#aaaaaa"
        base.bg_selected = "#000080"
        base.fg_primary = "#000000"
        base.fg_secondary = "#333333"
        base.accent = "#000080"
        base.accent_hover = "#0000aa"
        base.accent_bg = "#9999ff"
        base.border = "#808080"
        base.border_panel = "#808080"
        base.btn_bg = "#c0c0c0"
    base.extra_qss = f"""
QPushButton {{ border-radius: 0px; border: 2px solid {base.border}; text-transform: uppercase; }}
QFrame#panel {{ border-radius: 0px; border: 2px solid {base.border}; }}
QListWidget {{ border-radius: 0px; }}
QLabel#title {{ color: {base.accent}; font-family: {base.font_family}; }}
"""
    return base


def _solarized(base: ThemeTokens) -> ThemeTokens:
    """Solarized colour palette by Ethan Schoonover."""
    if base.mode == "dark":
        base.bg_window = "#002b36"
        base.bg_panel = "#073642"
        base.bg_input = "#073642"
        base.bg_hover = "#094656"
        base.bg_selected = "#1a3a3a"
        base.fg_primary = "#839496"
        base.fg_secondary = "#657b83"
        base.fg_muted = "#586e75"
        base.fg_disabled = "#4a5c62"
        base.accent = "#2aa198"
        base.accent_hover = "#35bdb4"
        base.accent_bg = "#0a3636"
        base.border = "#2c4a4a"
        base.border_panel = "#2c4a4a"
        base.border_input = "#264040"
        base.border_item = "#0a3030"
        base.btn_bg = "#073642"
        base.danger = "#dc322f"
    else:
        base.bg_window = "#fdf6e3"
        base.bg_panel = "#eee8d5"
        base.bg_input = "#fdf6e3"
        base.bg_hover = "#e6dfca"
        base.bg_selected = "#d4e8dc"
        base.fg_primary = "#657b83"
        base.fg_secondary = "#93a1a1"
        base.fg_muted = "#93a1a1"
        base.accent = "#2aa198"
        base.accent_hover = "#1f8078"
        base.accent_bg = "#d4ece8"
        base.border = "#c8c0aa"
        base.border_panel = "#c8c0aa"
        base.btn_bg = "#eee8d5"
        base.danger = "#dc322f"
    base.extra_qss = f"""
QLabel#title {{ color: {base.accent}; }}
"""
    return base


def _nord(base: ThemeTokens) -> ThemeTokens:
    """Nord colour palette — Arctic, north-bluish."""
    if base.mode == "dark":
        base.bg_window = "#2e3440"
        base.bg_panel = "#3b4252"
        base.bg_input = "#3b4252"
        base.bg_hover = "#434c5e"
        base.bg_selected = "#384860"
        base.fg_primary = "#eceff4"
        base.fg_secondary = "#d8dee9"
        base.fg_muted = "#7b88a0"
        base.accent = "#88c0d0"
        base.accent_hover = "#8fbcbb"
        base.accent_bg = "#2e3d4a"
        base.border = "#4c566a"
        base.border_panel = "#4c566a"
        base.border_input = "#434c5e"
        base.border_item = "#3b4252"
        base.btn_bg = "#3b4252"
        base.danger = "#bf616a"
    else:
        base.bg_window = "#eceff4"
        base.bg_panel = "#e5e9f0"
        base.bg_input = "#eceff4"
        base.bg_hover = "#d8dee9"
        base.bg_selected = "#cfe2ea"
        base.fg_primary = "#2e3440"
        base.fg_secondary = "#4c566a"
        base.fg_muted = "#7b88a0"
        base.accent = "#5e81ac"
        base.accent_hover = "#4c6d94"
        base.accent_bg = "#d4e2f0"
        base.border = "#d0d6e0"
        base.border_panel = "#d0d6e0"
        base.btn_bg = "#e5e9f0"
        base.danger = "#bf616a"
    base.extra_qss = f"""
QLabel#title {{ color: {base.accent}; }}
"""
    return base


def _dracula(base: ThemeTokens) -> ThemeTokens:
    """Dracula colour palette — popular dev theme."""
    if base.mode == "dark":
        base.bg_window = "#282a36"
        base.bg_panel = "#343746"
        base.bg_input = "#21222c"
        base.bg_hover = "#3a3d50"
        base.bg_selected = "#44475a"
        base.fg_primary = "#f8f8f2"
        base.fg_secondary = "#bfc1d0"
        base.fg_muted = "#6272a4"
        base.accent = "#bd93f9"
        base.accent_hover = "#caa8fb"
        base.accent_bg = "#362d50"
        base.border = "#44475a"
        base.border_panel = "#44475a"
        base.border_input = "#3a3d50"
        base.border_item = "#2c2e3a"
        base.btn_bg = "#343746"
        base.danger = "#ff5555"
        base.mute_active = "#ff5555"
        base.solo_active = "#f1fa8c"
    else:
        base.bg_window = "#f8f8f2"
        base.bg_panel = "#ededeb"
        base.bg_input = "#f8f8f2"
        base.bg_hover = "#e0e0d8"
        base.bg_selected = "#e6dff5"
        base.fg_primary = "#282a36"
        base.fg_secondary = "#44475a"
        base.fg_muted = "#6272a4"
        base.accent = "#7c4dff"
        base.accent_hover = "#651fff"
        base.accent_bg = "#e0d4f7"
        base.border = "#d0d0c8"
        base.border_panel = "#d0d0c8"
        base.btn_bg = "#ededeb"
        base.danger = "#ff5555"
    base.extra_qss = f"""
QLabel#title {{ color: {base.accent}; }}
"""
    return base


def _gameboy(base: ThemeTokens) -> ThemeTokens:
    """Original Game Boy — 4-shade green LCD palette."""
    # Game Boy always uses its own palette regardless of mode.
    base.bg_window = "#0f380f" if base.mode == "dark" else "#9bbc0f"
    base.bg_panel = "#306230" if base.mode == "dark" else "#8bac0f"
    base.bg_input = "#0f380f" if base.mode == "dark" else "#9bbc0f"
    base.bg_hover = "#306230" if base.mode == "dark" else "#8bac0f"
    base.bg_selected = "#8bac0f" if base.mode == "dark" else "#306230"
    base.fg_primary = "#9bbc0f" if base.mode == "dark" else "#0f380f"
    base.fg_secondary = "#8bac0f" if base.mode == "dark" else "#306230"
    base.fg_muted = "#306230" if base.mode == "dark" else "#8bac0f"
    base.fg_disabled = "#306230" if base.mode == "dark" else "#8bac0f"
    base.accent = "#9bbc0f" if base.mode == "dark" else "#0f380f"
    base.accent_hover = "#8bac0f" if base.mode == "dark" else "#306230"
    base.accent_bg = "#306230" if base.mode == "dark" else "#8bac0f"
    base.border = "#306230" if base.mode == "dark" else "#0f380f"
    base.border_panel = "#306230" if base.mode == "dark" else "#0f380f"
    base.border_input = "#306230" if base.mode == "dark" else "#306230"
    base.border_item = "#0f380f" if base.mode == "dark" else "#8bac0f"
    base.btn_bg = "#306230" if base.mode == "dark" else "#8bac0f"
    base.danger = "#9bbc0f" if base.mode == "dark" else "#0f380f"
    base.radius = "0px"
    base.radius_panel = "0px"
    base.font_family = "Consolas, Courier New, monospace"
    base.extra_qss = f"""
QPushButton {{ border-radius: 0px; border: 2px solid {base.border}; }}
QFrame#panel {{ border-radius: 0px; }}
QListWidget {{ border-radius: 0px; }}
QLabel#title {{ color: {base.accent}; font-family: {base.font_family}; }}
"""
    return base


# ────────────────────────────────────────────────────────────────────
# Registry
# ────────────────────────────────────────────────────────────────────

# Each entry: (display_name, description, builder_func)
THEME_CATALOGUE: dict[str, tuple[str, str, object]] = {
    "retro_neon":  ("Retro Neon",   "Original Koke16 — neon cyan on black",  _retro_neon),
    "aero_glass":  ("Aero Glass",   "Windows Vista/7-inspired translucent",  _aero_glass),
    "win11":       ("Windows 11",   "Modern Fluent UI / Mica-like",          _win11),
    "macos":       ("macOS",        "Apple Aqua-inspired rounded look",      _macos),
    "dos":         ("DOS / CGA",    "Retro MS-DOS terminal style",           _dos),
    "solarized":   ("Solarized",    "Ethan Schoonover's precision palette",  _solarized),
    "nord":        ("Nord",         "Arctic north-bluish colour scheme",     _nord),
    "dracula":     ("Dracula",      "Popular dark purple dev theme",         _dracula),
    "gameboy":     ("Game Boy",     "Original DMG 4-shade green LCD",        _gameboy),
}

DEFAULT_THEME = "retro_neon"
DEFAULT_MODE = "dark"


def get_theme_tokens(theme_id: str, mode: str) -> ThemeTokens:
    """Build final ``ThemeTokens`` for the given *theme_id* and *mode*."""
    base = _dark_base() if mode == "dark" else _light_base()
    _name, _desc, builder = THEME_CATALOGUE.get(theme_id, THEME_CATALOGUE[DEFAULT_THEME])
    return builder(base)


def get_theme_qss(theme_id: str, mode: str) -> str:
    """One-call convenience — returns the full QSS string."""
    return build_qss(get_theme_tokens(theme_id, mode))
